server:
  port: 9095
  
rabbit:
  hostname: 192.168.99.100
  port: 5672
  username: guest
  password: guest
  queueName: Inbox-Queue
  exchangeName: Telefonica-SendEmail
   
mail:  
  username: barunkumar.singh321@gmail.com
  password: cts2012##$
  host: smtp.gmail.com
  protocol: smtp
  port: 587