server:
  port: 9095
  
rabbit:
  hostname: 10.64.161.34
  port: 5672
  username: arpv
  password: arpv
  queueName: Inbox-Queue
  exchangeName: Telefonica-SendEmail
   
mail:  
  username: barun.singh@emc.com
  password:   
  host: 10.64.160.96
  protocol: smtp
  port: 25
  auth: false
  starttls: true  
  
  