server:
  port: 9091
  
rabbit:
  queueName: Inbox-Queue
  exchangeName: Telefonica-SendEmail
   
ldap:
  initialContextFactory: com.sun.jndi.ldap.LdapCtxFactory
  providerUrl: ldap://10.64.161.38:10389/o=SIUX
  securityPrincipal: uid=admin,ou=system
  securityCredentials: secret
  ouName: ARPV

database:
  username: rpadm
  password: Pa$$w0rd
  driverClass: com.microsoft.sqlserver.jdbc.SQLServerDriver
  url: jdbc:sqlserver://10.64.161.33:1433;database=RP	
  sqlString: select value from VInternalConfiguration where [RP].[dbo].[VInternalConfiguration].[Key]='emc.idp.user.auth.rpv.max.attempts'