server:
  port: 9095
  
rabbit:
  hostname: localhost
  port: 5672
  username: guest
  password: guest
  queueName: Inbox-Queue
  exchangeName: Telefonica-SendEmail
   
mail:  
  username: barun.singh@emc.com
  password:   
  host: 10.64.160.96
  protocol: smtp
  port: 25
  auth: false
  starttls: true  
  
  