server:
  port: 9091
  
rabbit:
  queueName: Inbox-Queue
  exchangeName: Telefonica-SendEmail
   
mail:  
  username: barun.singh@emc.com
  password:   
  host: 10.64.160.96
  protocol: smtp
  port: 25
  auth: false
  starttls: true  
  
  