server:
  port: 9095
  
rabbit:
  hostname: 
  port: 5672
  username: guest
  password: guest
  queueName: Inbox-Queue
  exchangeName: 
   
mail:  
  username: barunkumar.singh321@gmail.com
  password: 
  host: smtp.gmail.com
  protocol: smtp
  port: 587
